# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "version-checker"
main = "source/index.ts"

# Use workers.dev domain for development deployments
vars = { ENVIRONMENT = "dev" }
workers_dev = true

# Optimise script size
minify = true

# Do not send usage metrics
send_metrics = false

# Workers runtime
compatibility_date = "2023-12-06"

# Use my domain for production deployments
[env.production]
vars = { ENVIRONMENT = "production" }
route = { pattern = "versions.viral32111.dev", custom_domain = true }
