name: CI

on:
  push:
    paths:
      - '**'
    branches:
      - '**'
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    environment:
      name: cloudflare-workers
      url: ${{ vars.CLOUDFLARE_WORKER_URL }}
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version berry
  
      - name: Install dependencies
        run: yarn install

      - name: Build code
        run: yarn build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.19.0'
          packageManager: yarn

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            dist
            package.json
            yarn.lock
            README.md
            LICENSE.txt

  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: build
    environment:
      name: cloudflare-workers
      url: ${{ vars.CLOUDFLARE_WORKER_PRODUCTION_URL }}
    concurrency:
      group: cloudflare-workers
      cancel-in-progress: false
    permissions:
      contents: read
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version berry

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          environment: production
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.19.0'
          packageManager: yarn

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          path: artifact
      
      - name: Bundle build artifact
        run: zip -r ${{ github.event.repository.name }}.zip artifact

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          files: ${{ github.event.repository.name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
